# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HFsT7getNZ0v8LHAQYr7tlN1SEe1ZU_
"""

from google.colab import drive
drive.mount('/content/drive')

path="/content/task 2 unemployment.csv"

"""TASK 2
UN EMPLOYMENT RATE
"""

import pandas as pd
df=pd.read_csv("/content/task 2 unemployment.csv")
df.head()

df.info()

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

df.describe()

print(df.columns)

df.columns=df.columns.str.strip()

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
sns.histplot(df['Estimated Unemployment Rate (%)'],
            bins=20,
            kde=True)
plt.title('Distribution of Unemployment Rate')
plt.show()

top_states=df.groupby('Region')['Estimated Unemployment Rate (%)'].mean()
top_states=top_states.sort_values(ascending=False).head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=top_states.index,y=top_states.values,palette='viridis')
plt.title('Top 10 States by Unemployment Rate')
plt.xlabel('State')
plt.ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)
plt.show()

"""After mounting your Google Drive, you can list its contents to find the file you want to load. For example, to list the contents of your 'My Drive' folder:"""

sns.boxplot(
    x='Region.1',
    y='Estimated Unemployment Rate (%)',
    data=df,
)
plt.title('Unemployment Rate Across Regions')
plt.xlabel('Region')
plt.show()

plt.figure(figsize=(12,5))
df.groupby('Region.1')['Estimated Unemployment Rate (%)'].mean().plot()
plt.title('Average Unemployment Rate Across Regions')
plt.xlabel('Region')
plt.ylabel('Average Unemployment Rate (%)')
plt.show()

"""conclusion:

Distribution of Unemployment Rate: The histogram shows the general distribution of unemployment rates. We can observe if it's skewed, bimodal, or normally distributed, and identify common ranges.
Top 10 States by Unemployment Rate: The bar plot highlights the states with the highest average unemployment rates, indicating potential regional disparities or specific economic challenges in those areas.
Unemployment Rate Across Regions: The boxplot provides a visual comparison of unemployment rates across different regions (as represented by 'Region.1'). It helps in understanding the spread, median, and potential outliers in unemployment within each region, showing which regions might have consistently higher or more volatile unemployment.

"""